import 'package:freezed_annotation/freezed_annotation.dart';

part 'github_repository.freezed.dart';
part 'github_repository.g.dart';

@freezed
abstract class GitHubRepository with _$GitHubRepository {
  const factory GitHubRepository({String name, Map<String, dynamic> owner, String description, String language, int forks, int stargazersCount}) = _GitHubRepository;
  factory GitHubRepository.fromJson(Map<String, dynamic> json) => _$GitHubRepositoryFromJson(json);
}


  /* Sample response data for a given user
  {
    "id": 183292625,
    "node_id": "MDEwOlJlcG9zaXRvcnkxODMyOTI2MjU=",
    "name": "peliculas-flutter",
    "full_name": "Klerith/peliculas-flutter",
    "private": false,
    "owner": {
        "login": "Klerith",
        "id": 3438503,
        "node_id": "MDQ6VXNlcjM0Mzg1MDM=",
        "avatar_url": "https://avatars.githubusercontent.com/u/3438503?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/Klerith",
        "html_url": "https://github.com/Klerith",
        "followers_url": "https://api.github.com/users/Klerith/followers",
        "following_url": "https://api.github.com/users/Klerith/following{/other_user}",
        "gists_url": "https://api.github.com/users/Klerith/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/Klerith/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/Klerith/subscriptions",
        "organizations_url": "https://api.github.com/users/Klerith/orgs",
        "repos_url": "https://api.github.com/users/Klerith/repos",
        "events_url": "https://api.github.com/users/Klerith/events{/privacy}",
        "received_events_url": "https://api.github.com/users/Klerith/received_events",
        "type": "User",
        "site_admin": false
    },
    "html_url": "https://github.com/Klerith/peliculas-flutter",
    "description": "El repositorio del proyecto del curso de Flutter",
    "fork": false,
    "url": "https://api.github.com/repos/Klerith/peliculas-flutter",
    "forks_url": "https://api.github.com/repos/Klerith/peliculas-flutter/forks",
    "keys_url": "https://api.github.com/repos/Klerith/peliculas-flutter/keys{/key_id}",
    "collaborators_url": "https://api.github.com/repos/Klerith/peliculas-flutter/collaborators{/collaborator}",
    "teams_url": "https://api.github.com/repos/Klerith/peliculas-flutter/teams",
    "hooks_url": "https://api.github.com/repos/Klerith/peliculas-flutter/hooks",
    "issue_events_url": "https://api.github.com/repos/Klerith/peliculas-flutter/issues/events{/number}",
    "events_url": "https://api.github.com/repos/Klerith/peliculas-flutter/events",
    "assignees_url": "https://api.github.com/repos/Klerith/peliculas-flutter/assignees{/user}",
    "branches_url": "https://api.github.com/repos/Klerith/peliculas-flutter/branches{/branch}",
    "tags_url": "https://api.github.com/repos/Klerith/peliculas-flutter/tags",
    "blobs_url": "https://api.github.com/repos/Klerith/peliculas-flutter/git/blobs{/sha}",
    "git_tags_url": "https://api.github.com/repos/Klerith/peliculas-flutter/git/tags{/sha}",
    "git_refs_url": "https://api.github.com/repos/Klerith/peliculas-flutter/git/refs{/sha}",
    "trees_url": "https://api.github.com/repos/Klerith/peliculas-flutter/git/trees{/sha}",
    "statuses_url": "https://api.github.com/repos/Klerith/peliculas-flutter/statuses/{sha}",
    "languages_url": "https://api.github.com/repos/Klerith/peliculas-flutter/languages",
    "stargazers_url": "https://api.github.com/repos/Klerith/peliculas-flutter/stargazers",
    "contributors_url": "https://api.github.com/repos/Klerith/peliculas-flutter/contributors",
    "subscribers_url": "https://api.github.com/repos/Klerith/peliculas-flutter/subscribers",
    "subscription_url": "https://api.github.com/repos/Klerith/peliculas-flutter/subscription",
    "commits_url": "https://api.github.com/repos/Klerith/peliculas-flutter/commits{/sha}",
    "git_commits_url": "https://api.github.com/repos/Klerith/peliculas-flutter/git/commits{/sha}",
    "comments_url": "https://api.github.com/repos/Klerith/peliculas-flutter/comments{/number}",
    "issue_comment_url": "https://api.github.com/repos/Klerith/peliculas-flutter/issues/comments{/number}",
    "contents_url": "https://api.github.com/repos/Klerith/peliculas-flutter/contents/{+path}",
    "compare_url": "https://api.github.com/repos/Klerith/peliculas-flutter/compare/{base}...{head}",
    "merges_url": "https://api.github.com/repos/Klerith/peliculas-flutter/merges",
    "archive_url": "https://api.github.com/repos/Klerith/peliculas-flutter/{archive_format}{/ref}",
    "downloads_url": "https://api.github.com/repos/Klerith/peliculas-flutter/downloads",
    "issues_url": "https://api.github.com/repos/Klerith/peliculas-flutter/issues{/number}",
    "pulls_url": "https://api.github.com/repos/Klerith/peliculas-flutter/pulls{/number}",
    "milestones_url": "https://api.github.com/repos/Klerith/peliculas-flutter/milestones{/number}",
    "notifications_url": "https://api.github.com/repos/Klerith/peliculas-flutter/notifications{?since,all,participating}",
    "labels_url": "https://api.github.com/repos/Klerith/peliculas-flutter/labels{/name}",
    "releases_url": "https://api.github.com/repos/Klerith/peliculas-flutter/releases{/id}",
    "deployments_url": "https://api.github.com/repos/Klerith/peliculas-flutter/deployments",
    "created_at": "2019-04-24T19:19:38Z",
    "updated_at": "2020-12-30T16:01:36Z",
    "pushed_at": "2020-08-23T00:56:34Z",
    "git_url": "git://github.com/Klerith/peliculas-flutter.git",
    "ssh_url": "git@github.com:Klerith/peliculas-flutter.git",
    "clone_url": "https://github.com/Klerith/peliculas-flutter.git",
    "svn_url": "https://github.com/Klerith/peliculas-flutter",
    "homepage": null,
    "size": 103,
    "stargazers_count": 27,
    "watchers_count": 27,
    "language": "Dart",
    "has_issues": true,
    "has_projects": true,
    "has_downloads": true,
    "has_wiki": true,
    "has_pages": false,
    "forks_count": 30,
    "mirror_url": null,
    "archived": false,
    "disabled": false,
    "open_issues_count": 1,
    "license": null,
    "forks": 30,
    "open_issues": 1,
    "watchers": 27,
    "default_branch": "master",
    "score": 1.0
},
*/
